### ISSUE TITLE
How to add a custom marker and a custom ds model?

### ISSUE THREAD

**Issue by l2dev** [plattysoft/ArToolKitJpctBaseLib#12]
How to create a custom NFS marker let's say a qr code?

And how to put in my custom model instead of astronaut? Is simply adding a new .ds model enough?

**Comment by plattysoft** [comment]
This is not an issue, this is a question. Please don't use issues to ask questions in the future.

First, it is NFT (Natural Feature Trackers), not NFS.

Second, this library is a wrapper from ARToolkit, so all the process of training NFT, selecting markers, etc is done with ARToolkit.

Again, this library is just a wrapper that connects ARTookit with a 3D engine (jPCT-AE) all the details of tracking and markers are specific to ARTookit and all the specifics of 3D rendering are specific to jPCT-AE.

To learn more about NFT, check the official documentation: https://archive.artoolkit.org/documentation/doku.php?id=3_Marker_Training:marker_nft_training
