### ISSUE TITLE
Android studio dependency doesn't use latest version

### ISSUE THREAD

**Issue by elysio2** [plattysoft/ArToolKitJpctBaseLib#8]
My understanding is that i just have to add the compile() line to the build.gradle, and not manually download any files. However, that doesn't install the latest version (with the proper encapsulation for the renderer). Is it updated?

**Comment by plattysoft** [comment]
The latest changes / updates have not been packed into a new version yet.

**Comment by elysio2** [comment]
Would it be possible to release a , say, 0.9.1 version for this change? I've been using it as a library in android studio, but I'm about to hand off the project to another team and it would be much simpler if it could just be gradle.

**Comment by plattysoft** [comment]
Sorry for the long time to reply. I had very little time for my side projects lately.

Not sure if that changes will break backwards compatibility of anyone using this, but it is worth pushing.
